### ISSUE TITLE
Prefil date times with reasonable values

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-labs#17]
and settle on caps or CAPS for HH mm hh MM

Allow exact time (to the minute) 

Do not use AM / PM , use the 24hr clock.

(and, in general, this form is bad ... see if you can make it better)

![image](https://user-images.githubusercontent.com/5648894/56216426-52dbc080-6059-11e9-89e9-b921f31970f1.png)

**Comment by JaviCT** [comment]
Done
