### ISSUE TITLE
Allow three modes in events table; "raw_events"  "Detected_events" and "manual"

### ISSUE THREAD

**Issue by elyas20** [evercam/evercam-labs#191]
I have populated the DB with hand-made counting data. Add two modes to the trucks counting button like a radio button to switch between automatic and manual. To make a difference between them,  the "userid"="human" while automatic userid=" " (empty). check the DB using PGadmin to know more about the data.

Now we have data generated from Ahmet algorithm, you can identify it by "userid"= "ahmet"

**Comment by marcoherbst** [comment]
Different source of data for events:

There are 3 sources of data for the trucks count right now. 

1. My data you can identify it by userid= “” (empty  string)
2. Manual data  you can identify it by userid=”human”
3. Data generated by ahmet algorithm, you can identify it by userid=”ahmet”


On the interface, when you click on events you can add 3 choices :

1. Detection based( userid=””)
2. Manual counting(userid=”human”)
3. Algorithm generated (userid=”ahmet”)

When you choose one of these, the table shows only events from this source.

**Comment by Ali7862** [comment]
It's done.
