### ISSUE TITLE
Too slow to update the detections on snapshot change

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-labs#197]

**Comment by marcoherbst** [comment]
You might need to talk to @azharmalik3 if you don't know how to solve this. Include your decisions in this issue thread.

**Comment by Ali7862** [comment]
FYI
Actually previously we are running multiple queries within the loop this was too slow.  now we are getting results for all objects once on page load with a single query and saving into a variable and using it where we want. this very speeds as compared to previous.
