### ISSUE TITLE
Changes to Create Form

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-labs#62]
On this page:
![image](https://user-images.githubusercontent.com/5648894/56216532-828ac880-6059-11e9-8088-2db8d8464354.png)

Where it says # frames, this is bold and wrongly vertically aligned. Make it non-bold and correctly aligned and change from *316 Frames* to  316 Frames playing at 24 Frames Per Second (fps).

**Comment by JaviCT** [comment]
Done
